# Generated by Django 5.0.6 on 2024-06-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutritracker_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyWeight_goal', models.IntegerField()),
                ('bodyWeight_goal_deadline', models.DateField()),
            ],
        ),
    ]
